//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin
    {
        public string username { get; set; }
        public string password { get; set; }
        public string sec_qust { get; set; }
        public string sec_ans { get; set; }
    }
}
