//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public string username { get; set; }
        public string name { get; set; }
        public string password { get; set; }
        public string gender { get; set; }
        public string dob { get; set; }
        public string phone { get; set; }
        public string sec_ques { get; set; }
        public string sec_ans { get; set; }
    }
}
