//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class flightdetail
    {
        public string Flight_id { get; set; }
        public string Flight_name { get; set; }
        public string Departure { get; set; }
        public string Destination { get; set; }
        public string Departure_time { get; set; }
        public string Arrival_time { get; set; }
        public string Duration { get; set; }
        public int Total_Seats { get; set; }
        public string Price { get; set; }
        public string Date { get; set; }
    }
}
