//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class passengerdetail
    {
        public string Username { get; set; }
        public string Passenger_id { get; set; }
        public string Flight_id { get; set; }
        public string Date { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public string Age { get; set; }
        public string Adhar_number { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Meal_preference { get; set; }
        public string Seat { get; set; }
        public string Amount { get; set; }
        public string Status { get; set; }
        public Nullable<int> WaitingList { get; set; }
        public Nullable<int> No_of_Travellers { get; set; }
    
        public virtual flightdetail flightdetail { get; set; }
    }
}
